#############################################################################
# Makefile for building: qtqq
# Generated by qmake (2.01a) (Qt 4.8.0) on: ?? ?? 27 16:17:21 2012
# Project:  qtqq.pro
# Template: app
# Command: f:\qtsdk\desktop\qt\4.8.0\mingw\bin\qmake.exe -spec ..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\win32-g++ CONFIG+=release -o Makefile qtqq.pro
#############################################################################

first: release
install: release-install
uninstall: release-uninstall
MAKEFILE      = Makefile
QMAKE         = f:\qtsdk\desktop\qt\4.8.0\mingw\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y

COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
<<<<<<< HEAD
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		release \
		debug

release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: qtqq.pro  ../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/win32-g++/qmake.conf ../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/release.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/debug_and_release.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/rtti.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/exceptions.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/stl.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/shared.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/thread.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/win32/windows.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/4.8.0/mingw/mkspecs/features/include_source_dir.prf \
		f:/QtSDK/Desktop/Qt/4.8.0/mingw/lib/qtmain.prl
	$(QMAKE) -spec ..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\win32-g++ CONFIG+=release -o Makefile qtqq.pro
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\qconfig.pri:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\modules\qt_webkit_version.pri:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\qt_functions.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\qt_config.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\exclusive_builds.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\default_pre.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\win32\default_pre.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\release.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\debug_and_release.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\default_post.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\win32\default_post.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\win32\rtti.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\win32\exceptions.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\win32\stl.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\shared.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\warn_on.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\qt.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\win32\thread.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\moc.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\win32\windows.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\resources.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\uic.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\yacc.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\lex.prf:
..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\features\include_source_dir.prf:
f:\QtSDK\Desktop\Qt\4.8.0\mingw\lib\qtmain.prl:
qmake: qmake_all FORCE
	@$(QMAKE) -spec ..\..\QtSDK\Desktop\Qt\4.8.0\mingw\mkspecs\win32-g++ CONFIG+=release -o Makefile qtqq.pro

qmake_all: FORCE

make_default: release-make_default debug-make_default FORCE
make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
distclean: release-distclean debug-distclean FORCE
=======
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = cookie.cpp \
		login.cpp \
		main.cpp \
		mainpanel.cpp \
		request.cpp \
		types.cpp \
		qqpollthread.cpp \
		qqparsethread.cpp \
		qqfriendchatdlg.cpp \
		qqmsgtip.cpp \
		qqmsgcenter.cpp \
		qqmsg.cpp \
		qqgroupchatdlg.cpp \
		qqnamelabel.cpp \
		qqitemmodel.cpp \
		qqtextedit.cpp \
		imgloader.cpp \
		imgsender.cpp \
		groupimgsender.cpp \
		qqitem.cpp \
		friendinfodlg.cpp \
		qqfacepanel.cpp \
		friendimgsender.cpp \
		qqchatdlg.cpp \
		qqmsgsender.cpp moc_login.cpp \
		moc_mainpanel.cpp \
		moc_qqpollthread.cpp \
		moc_qqparsethread.cpp \
		moc_qqmsgcenter.cpp \
		moc_qqfriendchatdlg.cpp \
		moc_qqmsgtip.cpp \
		moc_qqgroupchatdlg.cpp \
		moc_qqnamelabel.cpp \
		moc_qqtextedit.cpp \
		moc_imgloader.cpp \
		moc_imgsender.cpp \
		moc_qqfacepanel.cpp \
		moc_qqchatdlg.cpp \
		qrc_img.cpp
OBJECTS       = cookie.o \
		login.o \
		main.o \
		mainpanel.o \
		request.o \
		types.o \
		qqpollthread.o \
		qqparsethread.o \
		qqfriendchatdlg.o \
		qqmsgtip.o \
		qqmsgcenter.o \
		qqmsg.o \
		qqgroupchatdlg.o \
		qqnamelabel.o \
		qqitemmodel.o \
		qqtextedit.o \
		imgloader.o \
		imgsender.o \
		groupimgsender.o \
		qqitem.o \
		friendinfodlg.o \
		qqfacepanel.o \
		friendimgsender.o \
		qqchatdlg.o \
		qqmsgsender.o \
		moc_login.o \
		moc_mainpanel.o \
		moc_qqpollthread.o \
		moc_qqparsethread.o \
		moc_qqmsgcenter.o \
		moc_qqfriendchatdlg.o \
		moc_qqmsgtip.o \
		moc_qqgroupchatdlg.o \
		moc_qqnamelabel.o \
		moc_qqtextedit.o \
		moc_imgloader.o \
		moc_imgsender.o \
		moc_qqfacepanel.o \
		moc_qqchatdlg.o \
		qrc_img.o
DIST          = ../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/release.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf \
		qtqq.pro
QMAKE_TARGET  = qtqq
DESTDIR       = 
TARGET        = qtqq

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_captcha.h ui_qqlogin.h ui_qqmainpanel.h ui_qqfriendchatdlg.h ui_qqgroupchatdlg.h ui_friendinfodlg.h ui_qqfacepanel.h ui_qqmsgtip.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtqq.pro  ../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++/qmake.conf ../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/release.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ -o Makefile qtqq.pro
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/linux.conf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-unix.conf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-unix.conf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/release.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/unix/thread.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/moc.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf:
../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec ../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/linux-g++ -o Makefile qtqq.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qtqq1.0.0 || $(MKDIR) .tmp/qtqq1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qtqq1.0.0/ && $(COPY_FILE) --parents cookie.h login.h mainpanel.h request.h types.h ui_login.h include/json/autolink.h include/json/config.h include/json/features.h include/json/forwards.h include/json/json.h include/json/reader.h include/json/writer.h include/json/value.h qqpollthread.h qqparsethread.h qqmsgcenter.h qqfriendchatdlg.h qqmsgtip.h qqmsg.h qqmsglistener.h qqgroupchatdlg.h qqnamelabel.h nameconvertor.h qqitemmodel.h qqtextedit.h imgloader.h imgsender.h utility.h groupimgsender.h qqitem.h friendinfodlg.h qqfacepanel.h qqchatdlg.h friendimgsender.h qqmsgsender.h friendimgloader.h groupimgloader.h .tmp/qtqq1.0.0/ && $(COPY_FILE) --parents img.qrc .tmp/qtqq1.0.0/ && $(COPY_FILE) --parents cookie.cpp login.cpp main.cpp mainpanel.cpp request.cpp types.cpp qqpollthread.cpp qqparsethread.cpp qqfriendchatdlg.cpp qqmsgtip.cpp qqmsgcenter.cpp qqmsg.cpp qqgroupchatdlg.cpp qqnamelabel.cpp qqitemmodel.cpp qqtextedit.cpp imgloader.cpp imgsender.cpp groupimgsender.cpp qqitem.cpp friendinfodlg.cpp qqfacepanel.cpp friendimgsender.cpp qqchatdlg.cpp qqmsgsender.cpp .tmp/qtqq1.0.0/ && $(COPY_FILE) --parents captcha.ui qqlogin.ui qqmainpanel.ui qqfriendchatdlg.ui qqgroupchatdlg.ui friendinfodlg.ui qqfacepanel.ui qqmsgtip.ui .tmp/qtqq1.0.0/ && (cd `dirname .tmp/qtqq1.0.0` && $(TAR) qtqq1.0.0.tar qtqq1.0.0 && $(COMPRESS) qtqq1.0.0.tar) && $(MOVE) `dirname .tmp/qtqq1.0.0`/qtqq1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qtqq1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
>>>>>>> origin/master
	-$(DEL_FILE) Makefile


check: first

<<<<<<< HEAD
release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
=======
mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_login.cpp moc_mainpanel.cpp moc_qqpollthread.cpp moc_qqparsethread.cpp moc_qqmsgcenter.cpp moc_qqfriendchatdlg.cpp moc_qqmsgtip.cpp moc_qqgroupchatdlg.cpp moc_qqnamelabel.cpp moc_qqtextedit.cpp moc_imgloader.cpp moc_imgsender.cpp moc_qqfacepanel.cpp moc_qqchatdlg.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_login.cpp moc_mainpanel.cpp moc_qqpollthread.cpp moc_qqparsethread.cpp moc_qqmsgcenter.cpp moc_qqfriendchatdlg.cpp moc_qqmsgtip.cpp moc_qqgroupchatdlg.cpp moc_qqnamelabel.cpp moc_qqtextedit.cpp moc_imgloader.cpp moc_imgsender.cpp moc_qqfacepanel.cpp moc_qqchatdlg.cpp
moc_login.cpp: types.h \
		login.h
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) login.h -o moc_login.cpp

moc_mainpanel.cpp: qqmsgtip.h \
		qqmsg.h \
		types.h \
		nameconvertor.h \
		qqmsgcenter.h \
		qqitem.h \
		qqpollthread.h \
		request.h \
		cookie.h \
		qqchatdlg.h \
		qqfacepanel.h \
		qqtextedit.h \
		imgloader.h \
		imgsender.h \
		qqmsglistener.h \
		qqmsgsender.h \
		qqparsethread.h \
		include/json/json.h \
		include/json/autolink.h \
		include/json/config.h \
		include/json/value.h \
		include/json/forwards.h \
		include/json/reader.h \
		include/json/features.h \
		include/json/writer.h \
		mainpanel.h
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) mainpanel.h -o moc_mainpanel.cpp

moc_qqpollthread.cpp: types.h \
		request.h \
		cookie.h \
		qqpollthread.h
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) qqpollthread.h -o moc_qqpollthread.cpp

moc_qqparsethread.cpp: qqmsg.h \
		types.h \
		include/json/json.h \
		include/json/autolink.h \
		include/json/config.h \
		include/json/value.h \
		include/json/forwards.h \
		include/json/reader.h \
		include/json/features.h \
		include/json/writer.h \
		qqparsethread.h
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) qqparsethread.h -o moc_qqparsethread.cpp

moc_qqmsgcenter.cpp: types.h \
		qqmsgcenter.h
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) qqmsgcenter.h -o moc_qqmsgcenter.cpp

moc_qqfriendchatdlg.cpp: qqmsg.h \
		types.h \
		nameconvertor.h \
		qqchatdlg.h \
		qqfacepanel.h \
		qqtextedit.h \
		imgloader.h \
		request.h \
		cookie.h \
		imgsender.h \
		qqmsglistener.h \
		qqmsgsender.h \
		qqfriendchatdlg.h
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) qqfriendchatdlg.h -o moc_qqfriendchatdlg.cpp

moc_qqmsgtip.cpp: qqmsg.h \
		types.h \
		nameconvertor.h \
		qqmsgtip.h
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) qqmsgtip.h -o moc_qqmsgtip.cpp

moc_qqgroupchatdlg.cpp: qqmsg.h \
		types.h \
		nameconvertor.h \
		qqchatdlg.h \
		qqfacepanel.h \
		qqtextedit.h \
		imgloader.h \
		request.h \
		cookie.h \
		imgsender.h \
		qqmsglistener.h \
		qqmsgsender.h \
		qqgroupchatdlg.h
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) qqgroupchatdlg.h -o moc_qqgroupchatdlg.cpp

moc_qqnamelabel.cpp: qqnamelabel.h
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) qqnamelabel.h -o moc_qqnamelabel.cpp

moc_qqtextedit.cpp: types.h \
		imgloader.h \
		qqmsg.h \
		request.h \
		cookie.h \
		imgsender.h \
		qqtextedit.h
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) qqtextedit.h -o moc_qqtextedit.cpp

moc_imgloader.cpp: qqmsg.h \
		types.h \
		request.h \
		cookie.h \
		imgloader.h
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) imgloader.h -o moc_imgloader.cpp

moc_imgsender.cpp: types.h \
		request.h \
		cookie.h \
		imgsender.h
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) imgsender.h -o moc_imgsender.cpp

moc_qqfacepanel.cpp: qqfacepanel.h
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) qqfacepanel.h -o moc_qqfacepanel.cpp

moc_qqchatdlg.cpp: qqfacepanel.h \
		qqtextedit.h \
		types.h \
		imgloader.h \
		qqmsg.h \
		request.h \
		cookie.h \
		imgsender.h \
		nameconvertor.h \
		qqmsglistener.h \
		qqmsgsender.h \
		qqchatdlg.h
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/moc $(DEFINES) $(INCPATH) qqchatdlg.h -o moc_qqchatdlg.cpp

compiler_rcc_make_all: qrc_img.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_img.cpp
qrc_img.cpp: img.qrc \
		images/Skins/system/1.45_4/main.jpg \
		images/LoginPanel/bg_white.png \
		images/LoginPanel/btn_close_normal.png \
		images/LoginPanel/bg_transparent.png \
		images/LoginPanel/btn_down.png \
		images/LoginPanel/btn_close_down.png \
		images/LoginPanel/btn_close_highlight.png \
		images/LoginPanel/btn_highlight.png \
		images/LoginPanel/btn_mini_down.png \
		images/LoginPanel/StdLoginBanner.png \
		images/LoginPanel/Main_Title.png \
		images/LoginPanel/btn_focus.png \
		images/LoginPanel/btn_mini_highlight.png \
		images/LoginPanel/btn_mini_normal.png \
		images/LoginPanel/Background/login_bg.png
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/rcc -name img img.qrc -o qrc_img.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_captcha.h ui_qqlogin.h ui_qqmainpanel.h ui_qqfriendchatdlg.h ui_qqgroupchatdlg.h ui_friendinfodlg.h ui_qqfacepanel.h ui_qqmsgtip.h
compiler_uic_clean:
	-$(DEL_FILE) ui_captcha.h ui_qqlogin.h ui_qqmainpanel.h ui_qqfriendchatdlg.h ui_qqgroupchatdlg.h ui_friendinfodlg.h ui_qqfacepanel.h ui_qqmsgtip.h
ui_captcha.h: captcha.ui
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic captcha.ui -o ui_captcha.h

ui_qqlogin.h: qqlogin.ui
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic qqlogin.ui -o ui_qqlogin.h

ui_qqmainpanel.h: qqmainpanel.ui
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic qqmainpanel.ui -o ui_qqmainpanel.h

ui_qqfriendchatdlg.h: qqfriendchatdlg.ui
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic qqfriendchatdlg.ui -o ui_qqfriendchatdlg.h

ui_qqgroupchatdlg.h: qqgroupchatdlg.ui
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic qqgroupchatdlg.ui -o ui_qqgroupchatdlg.h

ui_friendinfodlg.h: friendinfodlg.ui
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic friendinfodlg.ui -o ui_friendinfodlg.h

ui_qqfacepanel.h: qqfacepanel.ui
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic qqfacepanel.ui -o ui_qqfacepanel.h

ui_qqmsgtip.h: qqmsgtip.ui
	/home/zhanlang/QtSDK/Desktop/Qt/4.8.0/gcc/bin/uic qqmsgtip.ui -o ui_qqmsgtip.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

cookie.o: cookie.cpp cookie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cookie.o cookie.cpp

login.o: login.cpp login.h \
		types.h \
		ui_qqlogin.h \
		ui_captcha.h \
		request.h \
		cookie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o login.o login.cpp

main.o: main.cpp login.h \
		types.h \
		mainpanel.h \
		qqmsgtip.h \
		qqmsg.h \
		nameconvertor.h \
		qqmsgcenter.h \
		qqitem.h \
		qqpollthread.h \
		request.h \
		cookie.h \
		qqchatdlg.h \
		qqfacepanel.h \
		qqtextedit.h \
		imgloader.h \
		imgsender.h \
		qqmsglistener.h \
		qqmsgsender.h \
		qqparsethread.h \
		include/json/json.h \
		include/json/autolink.h \
		include/json/config.h \
		include/json/value.h \
		include/json/forwards.h \
		include/json/reader.h \
		include/json/features.h \
		include/json/writer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainpanel.o: mainpanel.cpp mainpanel.h \
		qqmsgtip.h \
		qqmsg.h \
		types.h \
		nameconvertor.h \
		qqmsgcenter.h \
		qqitem.h \
		qqpollthread.h \
		request.h \
		cookie.h \
		qqchatdlg.h \
		qqfacepanel.h \
		qqtextedit.h \
		imgloader.h \
		imgsender.h \
		qqmsglistener.h \
		qqmsgsender.h \
		qqparsethread.h \
		include/json/json.h \
		include/json/autolink.h \
		include/json/config.h \
		include/json/value.h \
		include/json/forwards.h \
		include/json/reader.h \
		include/json/features.h \
		include/json/writer.h \
		ui_qqmainpanel.h \
		qqitemmodel.h \
		qqfriendchatdlg.h \
		qqgroupchatdlg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainpanel.o mainpanel.cpp

request.o: request.cpp request.h \
		cookie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o request.o request.cpp

types.o: types.cpp types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o types.o types.cpp

qqpollthread.o: qqpollthread.cpp qqpollthread.h \
		types.h \
		request.h \
		cookie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqpollthread.o qqpollthread.cpp

qqparsethread.o: qqparsethread.cpp qqparsethread.h \
		qqmsg.h \
		types.h \
		include/json/json.h \
		include/json/autolink.h \
		include/json/config.h \
		include/json/value.h \
		include/json/forwards.h \
		include/json/reader.h \
		include/json/features.h \
		include/json/writer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqparsethread.o qqparsethread.cpp

qqfriendchatdlg.o: qqfriendchatdlg.cpp qqfriendchatdlg.h \
		qqmsg.h \
		types.h \
		nameconvertor.h \
		qqchatdlg.h \
		qqfacepanel.h \
		qqtextedit.h \
		imgloader.h \
		request.h \
		cookie.h \
		imgsender.h \
		qqmsglistener.h \
		qqmsgsender.h \
		ui_qqfriendchatdlg.h \
		friendimgsender.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqfriendchatdlg.o qqfriendchatdlg.cpp

qqmsgtip.o: qqmsgtip.cpp qqmsgtip.h \
		qqmsg.h \
		types.h \
		nameconvertor.h \
		ui_qqmsgtip.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqmsgtip.o qqmsgtip.cpp

qqmsgcenter.o: qqmsgcenter.cpp qqmsgcenter.h \
		types.h \
		qqmsg.h \
		qqmsgtip.h \
		nameconvertor.h \
		qqmsglistener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqmsgcenter.o qqmsgcenter.cpp

qqmsg.o: qqmsg.cpp qqmsg.h \
		types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqmsg.o qqmsg.cpp

qqgroupchatdlg.o: qqgroupchatdlg.cpp qqgroupchatdlg.h \
		qqmsg.h \
		types.h \
		nameconvertor.h \
		qqchatdlg.h \
		qqfacepanel.h \
		qqtextedit.h \
		imgloader.h \
		request.h \
		cookie.h \
		imgsender.h \
		qqmsglistener.h \
		qqmsgsender.h \
		groupimgsender.h \
		ui_qqgroupchatdlg.h \
		include/json/json.h \
		include/json/autolink.h \
		include/json/config.h \
		include/json/value.h \
		include/json/forwards.h \
		include/json/reader.h \
		include/json/features.h \
		include/json/writer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqgroupchatdlg.o qqgroupchatdlg.cpp

qqnamelabel.o: qqnamelabel.cpp qqnamelabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqnamelabel.o qqnamelabel.cpp

qqitemmodel.o: qqitemmodel.cpp qqitemmodel.h \
		types.h \
		qqitem.h \
		include/json/json.h \
		include/json/autolink.h \
		include/json/config.h \
		include/json/value.h \
		include/json/forwards.h \
		include/json/reader.h \
		include/json/features.h \
		include/json/writer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqitemmodel.o qqitemmodel.cpp

qqtextedit.o: qqtextedit.cpp qqtextedit.h \
		types.h \
		imgloader.h \
		qqmsg.h \
		request.h \
		cookie.h \
		imgsender.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqtextedit.o qqtextedit.cpp

imgloader.o: imgloader.cpp imgloader.h \
		qqmsg.h \
		types.h \
		request.h \
		cookie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imgloader.o imgloader.cpp

imgsender.o: imgsender.cpp imgsender.h \
		types.h \
		request.h \
		cookie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imgsender.o imgsender.cpp

groupimgsender.o: groupimgsender.cpp groupimgsender.h \
		types.h \
		request.h \
		cookie.h \
		imgsender.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o groupimgsender.o groupimgsender.cpp

qqitem.o: qqitem.cpp qqitem.h \
		types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqitem.o qqitem.cpp

friendinfodlg.o: friendinfodlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o friendinfodlg.o friendinfodlg.cpp

qqfacepanel.o: qqfacepanel.cpp qqfacepanel.h \
		ui_qqfacepanel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqfacepanel.o qqfacepanel.cpp

friendimgsender.o: friendimgsender.cpp friendimgsender.h \
		types.h \
		request.h \
		cookie.h \
		imgsender.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o friendimgsender.o friendimgsender.cpp

qqchatdlg.o: qqchatdlg.cpp qqchatdlg.h \
		qqfacepanel.h \
		qqtextedit.h \
		types.h \
		imgloader.h \
		qqmsg.h \
		request.h \
		cookie.h \
		imgsender.h \
		nameconvertor.h \
		qqmsglistener.h \
		qqmsgsender.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqchatdlg.o qqchatdlg.cpp

qqmsgsender.o: qqmsgsender.cpp qqmsgsender.h \
		request.h \
		cookie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qqmsgsender.o qqmsgsender.cpp

moc_login.o: moc_login.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_login.o moc_login.cpp

moc_mainpanel.o: moc_mainpanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainpanel.o moc_mainpanel.cpp

moc_qqpollthread.o: moc_qqpollthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qqpollthread.o moc_qqpollthread.cpp

moc_qqparsethread.o: moc_qqparsethread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qqparsethread.o moc_qqparsethread.cpp

moc_qqmsgcenter.o: moc_qqmsgcenter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qqmsgcenter.o moc_qqmsgcenter.cpp

moc_qqfriendchatdlg.o: moc_qqfriendchatdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qqfriendchatdlg.o moc_qqfriendchatdlg.cpp

moc_qqmsgtip.o: moc_qqmsgtip.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qqmsgtip.o moc_qqmsgtip.cpp

moc_qqgroupchatdlg.o: moc_qqgroupchatdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qqgroupchatdlg.o moc_qqgroupchatdlg.cpp

moc_qqnamelabel.o: moc_qqnamelabel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qqnamelabel.o moc_qqnamelabel.cpp

moc_qqtextedit.o: moc_qqtextedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qqtextedit.o moc_qqtextedit.cpp

moc_imgloader.o: moc_imgloader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imgloader.o moc_imgloader.cpp

moc_imgsender.o: moc_imgsender.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imgsender.o moc_imgsender.cpp

moc_qqfacepanel.o: moc_qqfacepanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qqfacepanel.o moc_qqfacepanel.cpp

moc_qqchatdlg.o: moc_qqchatdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qqchatdlg.o moc_qqchatdlg.cpp

qrc_img.o: qrc_img.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_img.o qrc_img.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

>>>>>>> origin/master
