######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 12 15:07:22 2012
######################################################################

TEMPLATE  = subdirs

CONFIG   += ordered
SUBDIRS += 3rdparty
SUBDIRS += src
